name: py310_voice_persona
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.1.1
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - dav1d=1.2.1
  - double-conversion=3.3.1
  - expat=2.7.3
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.12
  - graphite2=1.3.14
  - harfbuzz=11.0.0
  - hdf5=1.14.3
  - icu=75.1
  - imath=3.1.12
  - jasper=4.2.8
  - khronos-opencl-icd-loader=2024.10.24
  - krb5=1.21.3
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libasprintf=0.22.5
  - libavif16=1.1.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libclang13=21.1.7
  - libcurl=8.17.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.22.5
  - libglib=2.84.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libopencv=4.11.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.6
  - libpng=1.6.53
  - libprotobuf=5.28.3
  - librsvg=2.58.4
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - opencl-headers=2025.06.13
  - opencv=4.11.0
  - openexr=3.3.2
  - openh264=2.5.0
  - openssl=3.6.0
  - pango=1.56.3
  - pcre2=10.44
  - pip=25.3
  - pixman=0.46.4
  - pugixml=1.15
  - py-opencv=4.11.0
  - python=3.10.19
  - python_abi=3.10
  - qt6-main=6.8.3
  - rav1e=0.6.6
  - setuptools=80.9.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - svt-av1=2.3.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - cachetools==6.2.3
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - configargparse==1.7.1
      - conformer==0.3.2
      - cython==3.2.3
      - decorator==5.2.1
      - diffusers==0.29.0
      - distro==1.9.0
      - dlib==20.0.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - face-alignment==1.4.1
      - face-recognition==1.3.0
      - face-recognition-models==0.3.0
      - fastapi==0.115.6
      - fastapi-cli==0.0.4
      - ffmpy==1.0.0
      - filelock==3.20.0
      - flask==3.1.2
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - fvcore==0.1.5.post20221221
      - gast==0.7.0
      - gdown==5.1.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gradio==5.4.0
      - gradio-client==1.4.2
      - grpcio==1.57.0
      - grpcio-tools==1.57.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperpyyaml==1.2.2
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - inflect==7.3.1
      - intel-openmp==2021.4.0
      - iopath==0.1.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - kaldifst==1.7.17
      - keras==3.12.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.10.2
      - lightning==2.2.4
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mkl==2021.4.0
      - ml-dtypes==0.5.4
      - modelscope==1.20.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - namex==0.1.0
      - natsort==8.4.0
      - networkx==3.1
      - numba==0.63.1
      - numpy==1.26.4
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - onnx==1.16.0
      - onnxruntime==1.18.0
      - openai==2.13.0
      - openai-whisper==20231117
      - opt-einsum==3.4.0
      - optree==0.18.0
      - orjson==3.11.5
      - packaging==24.2
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pyreadline3==3.5.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.12
      - python-speech-features==0.6
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pywin32==311
      - pyworld==0.3.4
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rich==13.7.1
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - ruff==0.14.9
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soupsieve==2.8
      - soxr==1.0.0
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tbb==2021.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - tokenizers==0.21.4
      - tomlkit==0.12.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.51.3
      - typeguard==4.4.4
      - typer==0.20.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - uvicorn==0.30.0
      - websockets==12.0
      - werkzeug==3.1.4
      - wetext==0.0.4
      - wget==3.2
      - wrapt==2.0.1
      - yacs==0.1.8
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\tobyl\.conda\envs\py310_voice_persona
