name: py39_voice_persona
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.7.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - ffmpeg=6.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.8.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.86.2
  - glib-tools=2.86.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - harfbuzz=7.3.0
  - hdf5=1.14.1
  - icu=73.2
  - intel-openmp=2023.1.0
  - jasper=4.0.0
  - jinja2=3.1.6
  - khronos-opencl-icd-loader=2024.10.24
  - krb5=1.21.3
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=15.0.7
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.18
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.86.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libogg=1.3.5
  - libopencv=4.7.0
  - libopenvino=2023.2.0
  - libopenvino-auto-batch-plugin=2023.2.0
  - libopenvino-auto-plugin=2023.2.0
  - libopenvino-dev=2023.2.0
  - libopenvino-hetero-plugin=2023.2.0
  - libopenvino-intel-cpu-plugin=2023.2.0
  - libopenvino-intel-gpu-plugin=2023.2.0
  - libopenvino-ir-frontend=2023.2.0
  - libopenvino-onnx-frontend=2023.2.0
  - libopenvino-paddle-frontend=2023.2.0
  - libopenvino-python=2023.2.0
  - libopenvino-pytorch-frontend=2023.2.0
  - libopenvino-tensorflow-frontend=2023.2.0
  - libopenvino-tensorflow-lite-frontend=2023.2.0
  - libopus=1.6
  - libpng=1.6.53
  - libprotobuf=3.21.12
  - librsvg=2.56.3
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libusb=1.0.29
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.2.1
  - numpy-base=1.26.4
  - opencl-headers=2025.06.13
  - opencv=4.7.0
  - openh264=2.4.0
  - openssl=3.6.0
  - openvino=2023.2.0
  - openvino-telemetry=2025.2.0
  - pango=1.50.14
  - pcre2=10.46
  - pixman=0.46.4
  - pugixml=1.14
  - py-opencv=4.7.0
  - python=3.9.23
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - qt-main=5.15.8
  - sdl2=2.32.56
  - sdl3=3.2.28
  - setuptools=80.9.0
  - snappy=1.1.10
  - svt-av1=1.7.0
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - tk=8.6.13
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyascii==0.3.3
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - configargparse==1.7.1
      - conformer==0.3.2
      - contourpy==1.3.0
      - contractions==0.1.73
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - datasets==4.4.2
      - decorator==5.2.1
      - diffusers==0.29.0
      - dill==0.4.0
      - distro==1.9.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - face-alignment==1.4.1
      - fastapi==0.115.6
      - ffmpy==1.0.0
      - filelock==3.19.1
      - flask==2.3.3
      - flatbuffers==25.12.19
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - gast==0.4.0
      - gdown==5.2.0
      - google-auth==2.45.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.26.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperpyyaml==1.2.2
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inflect==7.0.0
      - iopath==0.1.10
      - itsdangerous==2.2.0
      - jmespath==0.10.0
      - joblib==1.5.3
      - kaldifst==1.7.17
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.10.2
      - lightning==2.2.4
      - lightning-utilities==0.15.2
      - llvmlite==0.43.0
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - modelscope==1.10.0
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - natsort==8.4.0
      - numba==0.60.0
      - numpy==1.23.5
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - onnxruntime==1.16.3
      - openai==1.30.5
      - openai-whisper==20231117
      - opencv-contrib-python==4.7.0.72
      - opt-einsum==3.4.0
      - orjson==3.11.5
      - oss2==2.19.1
      - packaging==24.2
      - pandas==1.5.2
      - pillow==10.4.0
      - pip==25.3
      - platformdirs==4.4.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==3.19.6
      - pyahocorasick==2.2.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyreadline3==3.5.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - python-speech-features==0.6
      - pytorch-lightning==2.6.0
      - pytorch3d==0.7.8
      - pytz==2025.2
      - pywin32==311
      - pyworld==0.3.5
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rich==14.2.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - ruff==0.14.10
      - safetensors==0.7.0
      - scikit-image==0.24.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - simplejson==3.20.2
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soupsieve==2.8.1
      - soxr==1.0.0
      - speechbrain==1.0.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.4
      - tensorflow-cpu==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-intel==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - textsearch==0.0.24
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tiktoken==0.12.0
      - tokenizers==0.21.4
      - tomli==2.3.0
      - tomlkit==0.12.0
      - torchaudio==2.5.1
      - torchmetrics==1.8.2
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.51.3
      - typer==0.20.1
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.30.0
      - websockets==12.0
      - werkzeug==3.1.4
      - wetext==0.1.2
      - wget==3.2
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yapf==0.43.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\tobyl\.conda\envs\py39_voice_persona
